import { useCallback, useEffect, useState } from 'react'
import type { KeyboardEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { AlertCircleIcon, AlertTriangleIcon, ArrowRightIcon, CheckCircle2Icon, HelpCircleIcon, LockIcon, MessageSquareIcon } from 'lucide-react'
import { getQuestion, getSession, submitAnswer } from '../api'
import type { AnswerResponse, QuestionResponse, SessionDetail } from '../api'
import { AppShell } from '@/components/AppShell'
import { Alert, AlertDescription, Badge, Button, Progress, Separator, Spinner, Textarea, Card } from '@/components/primitives'
const MAX_TURNS = 8
function BulletList({ text }: { text: string }) { const lines = text.split('\n').map(line => line.replace(/^[•-]\s*/, '').trim()).filter(Boolean); return lines.length ? <ul>{lines.map((line, index) => <li key={index}>{line}</li>)}</ul> : null }
export default function InterviewPage() { const { sessionId } = useParams<{ sessionId: string }>(); const navigate = useNavigate(); const [session, setSession] = useState<SessionDetail | null>(null); const [phase, setPhase] = useState<'loading' | 'question' | 'answering' | 'feedback'>('loading'); const [question, setQuestion] = useState<QuestionResponse | null>(null); const [answer, setAnswer] = useState(''); const [evaluation, setEvaluation] = useState<AnswerResponse | null>(null); const [turnNum, setTurnNum] = useState(0); const [error, setError] = useState('');
  const fetchQuestion = useCallback(async (sid: string) => { setPhase('loading'); setError(''); setAnswer(''); setEvaluation(null); try { const next = await getQuestion(sid); setQuestion(next); setTurnNum(next.turn_num); setPhase('question') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Failed to generate question.'); setPhase('question') } }, []); useEffect(() => { if (!sessionId) return; getSession(sessionId).then(value => { setSession(value); fetchQuestion(sessionId) }).catch(cause => setError(cause instanceof Error ? cause.message : 'Failed to load session.')) }, [sessionId, fetchQuestion]);
  async function handleSubmit() { if (!sessionId || !question || !answer.trim()) return; setPhase('answering'); setError(''); try { setEvaluation(await submitAnswer(sessionId, question.turn_id, answer.trim())); setPhase('feedback') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Evaluation failed.'); setPhase('question') } } function next() { if (turnNum >= MAX_TURNS) navigate(`/results/${sessionId}`); else if (sessionId) fetchQuestion(sessionId) } function blockClipboard(event: React.ClipboardEvent) { event.preventDefault() } function blockKeyCombo(event: KeyboardEvent<HTMLTextAreaElement>) { if ((event.ctrlKey || event.metaKey) && ['c', 'v', 'x'].includes(event.key.toLowerCase())) event.preventDefault() }
  const progress = Math.round((turnNum / MAX_TURNS) * 100); return <AppShell><div className="interview-layout"><nav className="interview-nav"><Link className="back-link" to="/">← Leave session</Link>{session && <Badge>{session.job_role}</Badge>}</nav><div className="progress-copy"><span>{turnNum ? `Question ${turnNum} of ${MAX_TURNS}` : 'Preparing your session'}</span><span>{progress}%</span></div><Progress value={progress} />{error && <Alert variant="destructive"><AlertCircleIcon size={17} /><AlertDescription>{error}</AlertDescription></Alert>}{phase === 'loading' && <Card className="loading"><div className="loading__inner"><Spinner /><p>Preparing your next question</p></div></Card>}{question && phase !== 'loading' && <><Card><div className="question-card__head"><p className="section-label">Question {question.turn_num}</p><Badge variant="outline">Interview prompt</Badge></div><div className="question-card__body">{question.question}</div></Card>{(phase === 'question' || phase === 'answering') && <Card className="answer-card"><div className="answer-card__head"><p className="section-label">Your answer</p><span className="lock-note"><LockIcon size={13} /> Copy and paste disabled</span></div><div className="answer-card__body"><Textarea rows={8} placeholder="Write your answer here. Include code where useful." value={answer} disabled={phase === 'answering'} onChange={event => setAnswer(event.target.value)} onCopy={blockClipboard} onPaste={blockClipboard} onCut={blockClipboard} onContextMenu={event => event.preventDefault()} onKeyDown={blockKeyCombo} /></div><div className="answer-card__footer"><Button className="full-button" disabled={!answer.trim() || phase === 'answering'} onClick={handleSubmit}>{phase === 'answering' ? <><Spinner /> Evaluating answer</> : <>Submit answer <ArrowRightIcon size={16} /></>}</Button></div></Card>}{phase === 'feedback' && evaluation && <Feedback evaluation={evaluation} onNext={next} last={turnNum >= MAX_TURNS} />}</>}</div></AppShell> }
function Feedback({ evaluation, onNext, last }: { evaluation: AnswerResponse; onNext: () => void; last: boolean }) { const label = evaluation.score >= 8 ? 'Strong answer' : evaluation.score >= 5 ? 'A solid start' : 'Keep building this skill'; return <Card className="feedback-card"><div className="feedback-card__head"><div className="score-ring">{evaluation.score}<small>/10</small></div><div><p><b>{label}</b></p><p className="muted">Your response has been evaluated.</p></div></div><div className="feedback-card__body">{evaluation.strengths && <div className="feedback-block feedback-block--good"><h3><CheckCircle2Icon size={14} /> Strengths</h3><BulletList text={evaluation.strengths} /></div>}{evaluation.weaknesses && <div className="feedback-block feedback-block--weak"><h3><AlertTriangleIcon size={14} /> Improve next</h3><BulletList text={evaluation.weaknesses} /></div>}{evaluation.feedback && <div className="feedback-block"><h3><MessageSquareIcon size={14} /> Feedback</h3><p>{evaluation.feedback}</p></div>}{evaluation.follow_up_question && <><Separator /><div className="feedback-block"><h3><HelpCircleIcon size={14} /> Follow-up question</h3><p>{evaluation.follow_up_question}</p></div></>}<Button className="full-button" onClick={onNext}>{last ? 'View final results' : 'Next question'} <ArrowRightIcon size={16} /></Button></div></Card> }
